INSERT INTO vendors (name) VALUES
                               ('ACI Limited'),
                               ('ACME Laboratories Ltd'),
                               ('Square Pharmaceuticals Ltd'),
                               ('Beximco Pharmaceuticals Ltd'),
                               ('Renata Limited'),
                               ('Incepta Pharmaceuticals Ltd'),
                               ('Opsonin Pharma Limited'),
                               ('Eskayef Pharmaceuticals Ltd'),
                               ('Aristopharma Ltd'),
                               ('Healthcare Pharmaceuticals Ltd'),
                               ('Nuvista Pharma Ltd'),
                               ('Astra Biopharmaceuticals Ltd'),
                               ('Beacon Pharmaceuticals Ltd'),
                               ('General Pharmaceuticals Ltd'),
                               ('Popular Pharmaceuticals Ltd'),
                               ('Unimed Unihealth Pharmaceuticals Ltd'),
                               ('ACI Formulations Ltd'),
                               ('Ziska Pharmaceuticals Ltd'),
                               ('Pharmasia Ltd'),
                               ('Globe Pharmaceuticals Ltd'),
                               ('Drug International Ltd'),
                               ('Rangs Pharmaceuticals Ltd'),
                               ('Orion Pharma Ltd'),
                               ('Biopharma Ltd'),
                               ('Sun Pharmaceutical Ltd'),
                               ('Chemist Laboratories Ltd'),
                               ('Ambee Pharmaceuticals Ltd'),
                               ('Delta Pharma Ltd'),
                               ('Kumudini Pharma Ltd'),
                               ('Active Fine Chemicals Ltd'),
                               ('ACI Animal Health'),
                               ('Advanced Chemical Industries Ltd'),
                               ('ACI Healthcare Ltd'),
                               ('Aristovet Ltd'),
                               ('Techno Drugs Ltd'),
                               ('Renata Animal Health'),
                               ('Sonear Laboratories Ltd'),
                               ('GlaxoSmithKline Bangladesh Ltd'),
                               ('Sanofi Bangladesh Ltd'),
                               ('Novartis Bangladesh Ltd'),
                               ('Bristol-Myers Squibb Bangladesh'),
                               ('Pfizer Bangladesh Ltd'),
                               ('Orion Infusion Ltd'),
                               ('Square Toiletries Ltd'),
                               ('Edruc Ltd'),
                               ('Novo Healthcare and Pharma Ltd'),
                               ('Opsonin Pharma Ltd'),
                               ('Ethical Drugs Ltd'),
                               ('Apex Pharma Ltd'),
                               ('Seema Pharmaceuticals Ltd'),
                               ('Cosmic Pharma Ltd'),
                               ('Orion Pharma Ltd'),
                               ('Bio Pharma Ltd'),
                               ('Popular Pharmaceuticals Ltd'),
                               ('Reman Drug Ltd'),
                               ('Julphar Bangladesh Ltd'),
                               ('Renata Limited'),
                               ('White Horse Pharma Ltd'),
                               ('Peacock Pharmaceuticals Ltd'),
                               ('Union Pharmaceuticals Ltd'),
                               ('Doctors Chemicals Works Ltd'),
                               ('Central Pharmaceuticals Ltd'),
                               ('NIPRO JMI Pharma Ltd'),
                               ('Modern Pharmaceuticals Ltd'),
                               ('Acme Laboratories Ltd'),
                               ('Eskayef Pharmaceuticals Ltd'),
                               ('The IBN SINA Pharmaceutical Industry Ltd'),
                               ('Medicon Pharmaceuticals Ltd'),
                               ('General Pharmaceuticals Ltd'),
                               ('Monico Pharmaceuticals Ltd'),
                               ('Supreme Pharmaceuticals Ltd'),
                               ('Globe Pharmaceuticals Ltd'),
                               ('Square Formulations Ltd'),
                               ('ACI Limited'),
                               ('Delta Pharma Ltd'),
                               ('Sonear Laboratories Ltd'),
                               ('Edruc Ltd'),
                               ('Pacific Pharmaceuticals Ltd'),
                               ('Nipa Pharmaceuticals Ltd'),
                               ('Organic Health Care Ltd'),
                               ('Aztec Pharmaceuticals Ltd'),
                               ('Bright Pharmaceuticals Ltd'),
                               ('Oriental Pharmaceuticals Ltd'),
                               ('Jayson Pharmaceuticals Ltd'),
                               ('Therap Pharmaceuticals Ltd'),
                               ('Amico Laboratories Ltd'),
                               ('Ambee Pharmaceuticals Ltd'),
                               ('Radiant Pharmaceuticals Ltd'),
                               ('Central Pharmaceuticals Ltd'),
                               ('MedRx Pharmaceuticals Ltd'),
                               ('Amicon Pharmaceuticals Ltd'),
                               ('Chemist Laboratories Ltd'),
                               ('Beacon Pharmaceuticals Ltd'),
                               ('Farmland Pharmaceuticals Ltd'),
                               ('Pacific Pharmaceuticals Ltd'),
                               ('Hamdard Laboratories (Waqf) Bangladesh'),
                               ('Neptune Laboratories Ltd'),
                               ('Kumudini Pharma Ltd'),
                               ('Rasa Pharmaceuticals Ltd'),
                               ('Gonoshasthaya Pharmaceuticals Ltd'),
                               ('BioMed Pharmaceuticals Ltd'),
                               ('MediChem Pharmaceuticals Ltd');

INSERT INTO generics (name) VALUES
                                ('Aceclofenac'),
                                ('Acetaminophen'),
                                ('Acyclovir'),
                                ('Albuterol'),
                                ('Allopurinol'),
                                ('Amitriptyline'),
                                ('Amlodipine'),
                                ('Amoxicillin'),
                                ('Aripiprazole'),
                                ('Aspirin'),
                                ('Atorvastatin'),
                                ('Azithromycin'),
                                ('Baclofen'),
                                ('Beclomethasone'),
                                ('Benzonatate'),
                                ('Betamethasone'),
                                ('Bisoprolol'),
                                ('Budesonide'),
                                ('Buprenorphine'),
                                ('Bupropion'),
                                ('Captopril'),
                                ('Carbamazepine'),
                                ('Cefalexin'),
                                ('Celecoxib'),
                                ('Cephalexin'),
                                ('Cetirizine'),
                                ('Ciprofloxacin'),
                                ('Citalopram'),
                                ('Clindamycin'),
                                ('Clobetasol'),
                                ('Clomiphene'),
                                ('Clonazepam'),
                                ('Clopidogrel'),
                                ('Codeine'),
                                ('Colchicine'),
                                ('Cyclobenzaprine'),
                                ('Dexamethasone'),
                                ('Diazepam'),
                                ('Diclofenac'),
                                ('Digoxin'),
                                ('Diltiazem'),
                                ('Diphenhydramine'),
                                ('Doxycycline'),
                                ('Duloxetine'),
                                ('Enalapril'),
                                ('Escitalopram'),
                                ('Esomeprazole'),
                                ('Famotidine'),
                                ('Felodipine'),
                                ('Fentanyl'),
                                ('Fluconazole'),
                                ('Fluoxetine'),
                                ('Fluticasone'),
                                ('Furosemide'),
                                ('Gabapentin'),
                                ('Gliclazide'),
                                ('Glimepiride'),
                                ('Glipizide'),
                                ('Hydrochlorothiazide'),
                                ('Hydrocodone'),
                                ('Hydrocortisone'),
                                ('Ibuprofen'),
                                ('Indomethacin'),
                                ('Ipratropium'),
                                ('Isosorbide'),
                                ('Itraconazole'),
                                ('Ketoconazole'),
                                ('Labetalol'),
                                ('Lamotrigine'),
                                ('Lansoprazole'),
                                ('Lisinopril'),
                                ('Lorazepam'),
                                ('Losartan'),
                                ('Lovastatin'),
                                ('Metformin'),
                                ('Methotrexate'),
                                ('Metoprolol'),
                                ('Metronidazole'),
                                ('Montelukast'),
                                ('Morphine'),
                                ('Naproxen'),
                                ('Nifedipine'),
                                ('Nitrofurantoin'),
                                ('Nitroglycerin'),
                                ('Olanzapine'),
                                ('Omeprazole'),
                                ('Ondansetron'),
                                ('Oseltamivir'),
                                ('Pantoprazole'),
                                ('Paracetamol'),
                                ('Phenytoin'),
                                ('Prednisone'),
                                ('Propranolol'),
                                ('Ranitidine'),
                                ('Risperidone'),
                                ('Rosuvastatin'),
                                ('Sertraline'),
                                ('Simvastatin'),
                                ('Spironolactone'),
                                ('Sulfasalazine'),
                                ('Sumatriptan'),
                                ('Tamsulosin'),
                                ('Terbinafine'),
                                ('Tramadol'),
                                ('Trazodone'),
                                ('Valacyclovir'),
                                ('Valsartan'),
                                ('Venlafaxine'),
                                ('Warfarin'),
                                ('Zolpidem');


INSERT INTO doctors (name, bmdc) VALUES
                                     ('Dr. Ashraful Islam', 1000),
                                     ('Dr. Farzana Haque', 1001),
                                     ('Dr. Anwar Hossain', 1002),
                                     ('Dr. Mahbub Alam', 1003),
                                     ('Dr. Sultana Begum', 1004),
                                     ('Dr. Shakil Ahmed', 1005),
                                     ('Dr. Khaled Mahmud', 1006),
                                     ('Dr. Nusrat Jahan', 1007),
                                     ('Dr. Mizanur Rahman', 1008),
                                     ('Dr. Fahmida Khatun', 1009),
                                     ('Dr. Jamil Ahmed', 1010),
                                     ('Dr. Arifur Rahman', 1011),
                                     ('Dr. Nargis Akhter', 1012),
                                     ('Dr. Kamrul Hasan', 1013),
                                     ('Dr. Taslima Akter', 1014),
                                     ('Dr. Sayed Ali', 1015),
                                     ('Dr. Farid Ahmed', 1016),
                                     ('Dr. Laila Begum', 1017),
                                     ('Dr. Zahir Uddin', 1018),
                                     ('Dr. Rehana Akter', 1019),
                                     ('Dr. Tareq Aziz', 1020),
                                     ('Dr. Mahmud Hasan', 1021),
                                     ('Dr. Sadia Sultana', 1022),
                                     ('Dr. Anisur Rahman', 1023),
                                     ('Dr. Sharmin Akter', 1024),
                                     ('Dr. Shafiqul Islam', 1025),
                                     ('Dr. Hamida Khatun', 1026),
                                     ('Dr. Iftekhar Ahmed', 1027),
                                     ('Dr. Maruf Ahmed', 1028),
                                     ('Dr. Nazrul Islam', 1029),
                                     ('Dr. Rumana Haque', 1030),
                                     ('Dr. Morshed Alam', 1031),
                                     ('Dr. Tasnim Jahan', 1032),
                                     ('Dr. Asif Mahmud', 1033),
                                     ('Dr. Munira Begum', 1034),
                                     ('Dr. Shahidul Islam', 1035),
                                     ('Dr. Hosne Ara', 1036),
                                     ('Dr. Feroz Ahmed', 1037),
                                     ('Dr. Anjuman Ara', 1038),
                                     ('Dr. Rezaul Karim', 1039),
                                     ('Dr. Sheuli Akter', 1040),
                                     ('Dr. Mamunur Rashid', 1041),
                                     ('Dr. Selina Begum', 1042),
                                     ('Dr. Tahmina Akhter', 1043),
                                     ('Dr. Abu Bakar', 1044),
                                     ('Dr. Nilufar Yasmin', 1045),
                                     ('Dr. Shirin Akhter', 1046),
                                     ('Dr. Zahid Hossain', 1047),
                                     ('Dr. Sanjida Islam', 1048),
                                     ('Dr. Rashedul Islam', 1049),
                                     ('Dr. Momena Begum', 1050),
                                     ('Dr. Azad Hossain', 1051),
                                     ('Dr. Sohana Akter', 1052),
                                     ('Dr. Rafiqul Islam', 1053),
                                     ('Dr. Fariha Anjum', 1054),
                                     ('Dr. Hasibur Rahman', 1055),
                                     ('Dr. Saira Banu', 1056),
                                     ('Dr. Manjurul Islam', 1057),
                                     ('Dr. Lubna Yasmin', 1058),
                                     ('Dr. Masud Karim', 1059),
                                     ('Dr. Najma Akter', 1060),
                                     ('Dr. Latifur Rahman', 1061),
                                     ('Dr. Sazia Khatun', 1062),
                                     ('Dr. Ruhul Amin', 1063),
                                     ('Dr. Sabrina Yasmin', 1064),
                                     ('Dr. Tanjina Akhter', 1065),
                                     ('Dr. Obaidul Haque', 1066),
                                     ('Dr. Sultana Jahan', 1067),
                                     ('Dr. Mobarak Hossain', 1068),
                                     ('Dr. Ferdousi Begum', 1069),
                                     ('Dr. Alamgir Kabir', 1070),
                                     ('Dr. Sufia Khatun', 1071),
                                     ('Dr. Wahidul Islam', 1072),
                                     ('Dr. Nafisa Anjum', 1073),
                                     ('Dr. Alam Ara', 1074),
                                     ('Dr. Golam Rabbani', 1075),
                                     ('Dr. Tamanna Rahman', 1076),
                                     ('Dr. Mahmudul Hasan', 1077),
                                     ('Dr. Parveen Akter', 1078),
                                     ('Dr. Badrul Islam', 1079),
                                     ('Dr. Hasina Begum', 1080),
                                     ('Dr. Zakir Hossain', 1081),
                                     ('Dr. Roksana Akhter', 1082),
                                     ('Dr. Habibur Rahman', 1083),
                                     ('Dr. Rosy Akter', 1084),
                                     ('Dr. Naimul Islam', 1085),
                                     ('Dr. Jannatul Ferdous', 1086),
                                     ('Dr. Shakhawat Hossain', 1087),
                                     ('Dr. Ayesha Siddika', 1088),
                                     ('Dr. Shahed Karim', 1089),
                                     ('Dr. Labiba Rahman', 1090),
                                     ('Dr. Faizur Rahman', 1091),
                                     ('Dr. Sabiha Sultana', 1092),
                                     ('Dr. Aftab Uddin', 1093),
                                     ('Dr. Razia Sultana', 1094),
                                     ('Dr. Asma Akter', 1095),
                                     ('Dr. Mahmudul Islam', 1096),
                                     ('Dr. Muslima Begum', 1097),
                                     ('Dr. Arman Hossain', 1098),
                                     ('Dr. Rabeya Khatun', 1099);

INSERT INTO patients (name, phone, age) VALUES
                                            ('Abul Kalam Azad', '01711326980', '25'),
                                            ('Fatema Begum', '01711326981', '30'),
                                            ('Rafiqul Islam', '01711326982', '45'),
                                            ('Nazmul Huda', '01711326983', '35'),
                                            ('Sultana Kamal', '01711326984', '40'),
                                            ('Shakil Ahmed', '01711326985', '50'),
                                            ('Khaleda Rahman', '01711326986', '28'),
                                            ('Mamunur Rashid', '01711326987', '33'),
                                            ('Nusrat Jahan', '01711326988', '37'),
                                            ('Farhana Islam', '01711326989', '26'),
                                            ('Mizanur Rahman', '01711326990', '32'),
                                            ('Shahida Akter', '01711326991', '29'),
                                            ('Kamrul Hasan', '01711326992', '36'),
                                            ('Fahmida Khatun', '01711326993', '27'),
                                            ('Anwar Hossain', '01711326994', '31'),
                                            ('Mahbub Alam', '01711326995', '34'),
                                            ('Sultana Begum', '01711326996', '38'),
                                            ('Rezaul Karim', '01711326997', '41'),
                                            ('Tahmina Akter', '01711326998', '44'),
                                            ('Abdul Latif', '01711326999', '47'),
                                            ('Hosne Ara', '01711327000', '49'),
                                            ('Rafiqul Alam', '01711327001', '39'),
                                            ('Jamil Ahmed', '01711327002', '43'),
                                            ('Zakir Hossain', '01711327003', '48'),
                                            ('Labiba Rahman', '01711327004', '46'),
                                            ('Sazia Khatun', '01711327005', '42'),
                                            ('Munira Begum', '01711327006', '50'),
                                            ('Aftab Uddin', '01711327007', '51'),
                                            ('Sabrina Yasmin', '01711327008', '28'),
                                            ('Tasnim Jahan', '01711327009', '25'),
                                            ('Shirin Akhter', '01711327010', '29'),
                                            ('Momena Begum', '01711327011', '30'),
                                            ('Obaidul Haque', '01711327012', '31'),
                                            ('Fariha Anjum', '01711327013', '32'),
                                            ('Manjurul Islam', '01711327014', '33'),
                                            ('Rokeya Khatun', '01711327015', '34'),
                                            ('Hasibur Rahman', '01711327016', '35'),
                                            ('Latifur Rahman', '01711327017', '36'),
                                            ('Asma Akter', '01711327018', '37'),
                                            ('Ayesha Siddika', '01711327019', '38'),
                                            ('Rubina Yasmin', '01711327020', '39'),
                                            ('Sadiya Khan', '01711327021', '40'),
                                            ('Mobarak Hossain', '01711327022', '41'),
                                            ('Wahidul Islam', '01711327023', '42'),
                                            ('Tahmid Rahman', '01711327024', '43'),
                                            ('Feroz Ahmed', '01711327025', '44'),
                                            ('Parveen Akhter', '01711327026', '45'),
                                            ('Badrul Islam', '01711327027', '46'),
                                            ('Hasina Begum', '01711327028', '47'),
                                            ('Nafisa Anjum', '01711327029', '48'),
                                            ('Arman Hossain', '01711327030', '49'),
                                            ('Jannatul Ferdous', '01711327031', '50'),
                                            ('Naimul Islam', '01711327032', '51'),
                                            ('Morshed Alam', '01711327033', '28'),
                                            ('Mahmudul Hasan', '01711327034', '29'),
                                            ('Rosy Akter', '01711327035', '30'),
                                            ('Saira Banu', '01711327036', '31'),
                                            ('Tareq Aziz', '01711327037', '32'),
                                            ('Sufia Khatun', '01711327038', '33'),
                                            ('Shahidul Islam', '01711327039', '34'),
                                            ('Shakhawat Hossain', '01711327040', '35'),
                                            ('Afsana Begum', '01711327041', '36'),
                                            ('Mahmud Hasan', '01711327042', '37'),
                                            ('Nafisa Rahman', '01711327043', '38'),
                                            ('Ruhul Amin', '01711327044', '39'),
                                            ('Shahed Karim', '01711327045', '40'),
                                            ('Razia Sultana', '01711327046', '41'),
                                            ('Tamanna Rahman', '01711327047', '42'),
                                            ('Sabiha Sultana', '01711327048', '43'),
                                            ('Zahir Uddin', '01711327049', '44'),
                                            ('Shakila Ahmed', '01711327050', '45'),
                                            ('Kamrul Hasan', '01711327051', '46'),
                                            ('Hasibur Rahman', '01711327052', '47'),
                                            ('Labiba Rahman', '01711327053', '48'),
                                            ('Obaidul Haque', '01711327054', '49'),
                                            ('Mobarak Hossain', '01711327055', '50'),
                                            ('Faizur Rahman', '01711327056', '51'),
                                            ('Farid Ahmed', '01711327057', '52'),
                                            ('Zahid Hossain', '01711327058', '28'),
                                            ('Mizanur Rahman', '01711327059', '29'),
                                            ('Taslim Uddin', '01711327060', '30'),
                                            ('Sultana Jahan', '01711327061', '31'),
                                            ('Rehana Akter', '01711327062', '32'),
                                            ('Tanjina Akhter', '01711327063', '33'),
                                            ('Rahim Uddin', '01711327064', '34'),
                                            ('Rezaul Karim', '01711327065', '35'),
                                            ('Mahmudul Islam', '01711327066', '36'),
                                            ('Shirin Akhter', '01711327067', '37'),
                                            ('Nilufar Yasmin', '01711327068', '38'),
                                            ('Nusrat Jahan', '01711327069', '39'),
                                            ('Arman Hossain', '01711327070', '40'),
                                            ('Jamil Ahmed', '01711327071', '41'),
                                            ('Parveen Akhter', '01711327072', '42'),
                                            ('Tahmina Akhter', '01711327073', '43'),
                                            ('Fahmida Khatun', '01711327074', '44'),
                                            ('Fariha Anjum', '01711327075', '45'),
                                            ('Sadia Sultana', '01711327076', '46'),
                                            ('Ayesha Siddika', '01711327077', '47'),
                                            ('Khaleda Rahman', '01711327078', '48'),
                                            ('Munira Begum', '01711327079', '49'),
                                            ('Tahmid Rahman', '01711327080', '50'),
                                            ('Mahmudul Islam', '01711327081', '51'),
                                            ('Manjurul Islam', '01711327082', '28'),
                                            ('Sonia Akhter', '01711327083', '29'),
                                            ('Sharmin Jahan', '01711327084', '30'),
                                            ('Tanjina Akhter', '01711327085', '31'),
                                            ('Zakir Hossain', '01711327086', '32'),
                                            ('Rashedul Islam', '01711327087', '33'),
                                            ('Sultana Kamal', '01711327088', '34'),
                                            ('Najmul Huda', '01711327089', '35'),
                                            ('Fatema Begum', '01711327090', '36'),
                                            ('Mamunur Rashid', '01711327091', '37'),
                                            ('Rafiqul Islam', '01711327092', '38'),
                                            ('Asma Akter', '01711327093', '39'),
                                            ('Saira Banu', '01711327094', '40'),
                                            ('Parveen Akhter', '01711327095', '41'),
                                            ('Rosy Akter', '01711327096', '42'),
                                            ('Nusrat Jahan', '01711327097', '43'),
                                            ('Rehana Akter', '01711327098', '44'),
                                            ('Sultana Jahan', '01711327099', '45');

INSERT INTO drugs (drug_name, formula, strength, generic_id, vendor_id)VALUES
                                                                           ('Napa', 'Tablet', '500mg', 90, 4),
                                                                           ('Amoxicillin', 'Capsule', '500mg', 2, 2),
                                                                           ('Cetirizine', 'Liquid', '5mg/5ml', 3, 3),
                                                                           ('Insulin Glargine', 'Injection', '100U/ml', 4, 4),
                                                                           ('Clotrimazole', 'Cream', '1%', 5, 5),
                                                                           ('Hydrocortisone', 'Ointment', '2.5%', 6, 6),
                                                                           ('Metformin', 'Tablet', '500mg', 7, 7),
                                                                           ('Omeprazole', 'Capsule', '20mg', 8, 8),
                                                                           ('Salbutamol', 'Inhaler', '100mcg', 9, 9),
                                                                           ('Loratadine', 'Syrup', '5mg/5ml', 10, 10),
                                                                           ('Paracetamol', 'Tablet', '500mg', 11, 11),
                                                                           ('Aspirin', 'Tablet', '81mg', 12, 1),
                                                                           ('Azithromycin', 'Tablet', '250mg', 13, 2),
                                                                           ('Doxycycline', 'Capsule', '100mg', 14, 3),
                                                                           ('Furosemide', 'Injection', '10mg/ml', 15, 4),
                                                                           ('Gabapentin', 'Tablet', '300mg', 16, 5),
                                                                           ('Lisinopril', 'Tablet', '10mg', 17, 6),
                                                                           ('Montelukast', 'Tablet', '10mg', 18, 7),
                                                                           ('Prednisolone', 'Liquid', '15mg/5ml', 19, 8),
                                                                           ('Ranitidine', 'Tablet', '150mg', 20, 9),
                                                                           ('Simvastatin', 'Tablet', '20mg', 1, 10),
                                                                           ('Amlodipine', 'Tablet', '5mg', 2, 11),
                                                                           ('Ciprofloxacin', 'Tablet', '500mg', 3, 1),
                                                                           ('Fluconazole', 'Capsule', '150mg', 4, 2),
                                                                           ('Ibuprofen', 'Suspension', '100mg/5ml', 5, 3),
                                                                           ('Metronidazole', 'Tablet', '400mg', 6, 4),
                                                                           ('Tramadol', 'Capsule', '50mg', 7, 5),
                                                                           ('Duloxetine', 'Capsule', '30mg', 8, 6),
                                                                           ('Gabapentin', 'Capsule', '300mg', 9, 7),
                                                                           ('Levothyroxine', 'Tablet', '50mcg', 10, 8),
                                                                           ('Metformin', 'Tablet', '850mg', 11, 9),
                                                                           ('Naprosyn', 'Tablet', '500mg', 12, 10),
                                                                           ('Sildenafil', 'Tablet', '50mg', 13, 11),
                                                                           ('Tadalafil', 'Tablet', '5mg', 14, 1),
                                                                           ('Atorvastatin', 'Tablet', '10mg', 15, 2),
                                                                           ('Diclofenac', 'Gel', '1%', 16, 3),
                                                                           ('Esomeprazole', 'Tablet', '40mg', 17, 4),
                                                                           ('Folic Acid', 'Tablet', '5mg', 18, 5),
                                                                           ('Glyburide', 'Tablet', '5mg', 19, 6),
                                                                           ('Hydrochlorothiazide', 'Tablet', '25mg', 20, 7),
                                                                           ('Ivermectin', 'Tablet', '3mg', 1, 8),
                                                                           ('Lamotrigine', 'Tablet', '100mg', 2, 9),
                                                                           ('Methylphenidate', 'Tablet', '10mg', 3, 10),
                                                                           ('Nitrofurantoin', 'Capsule', '100mg', 4, 11),
                                                                           ('Ondansetron', 'Tablet', '8mg', 5, 1),
                                                                           ('Pantoprazole', 'Tablet', '40mg', 6, 2),
                                                                           ('Quetiapine', 'Tablet', '25mg', 7, 3),
                                                                           ('Rosuvastatin', 'Tablet', '10mg', 8, 4),
                                                                           ('Sertraline', 'Tablet', '50mg', 9, 5),
                                                                           ('Topiramate', 'Tablet', '25mg', 10, 6),
                                                                           ('Valacyclovir', 'Tablet', '500mg', 11, 7),
                                                                           ('Warfarin', 'Tablet', '5mg', 12, 8),
                                                                           ('Xarelto', 'Tablet', '20mg', 13, 9),
                                                                           ('Yasmin', 'Tablet', '3mg', 14, 10),
                                                                           ('Zolpidem', 'Tablet', '10mg', 15, 11),
                                                                           ('Acetaminophen', 'Tablet', '325mg', 16, 1),
                                                                           ('Benazepril', 'Tablet', '10mg', 17, 2),
                                                                           ('Candesartan', 'Tablet', '16mg', 18, 3),
                                                                           ('Desloratadine', 'Tablet', '5mg', 19, 4),
                                                                           ('Erythromycin', 'Tablet', '500mg', 20, 5),
                                                                           ('Fluoxetine', 'Capsule', '20mg', 1, 6),
                                                                           ('Glipizide', 'Tablet', '10mg', 2, 7),
                                                                           ('Hydroxychloroquine', 'Tablet', '200mg', 3, 8),
                                                                           ('Indomethacin', 'Capsule', '25mg', 4, 9),
                                                                           ('Januvia', 'Tablet', '100mg', 5, 10),
                                                                           ('Keppra', 'Tablet', '500mg', 6, 11),
                                                                           ('Levofloxacin', 'Tablet', '500mg', 7, 1),
                                                                           ('Methotrexate', 'Tablet', '2.5mg', 8, 2),
                                                                           ('Naproxen', 'Tablet', '250mg', 9, 3),
                                                                           ('Olanzapine', 'Tablet', '10mg', 10, 4),
                                                                           ('Propranolol', 'Tablet', '40mg', 11, 5),
                                                                           ('Quinapril', 'Tablet', '20mg', 12, 6),
                                                                           ('Risperidone', 'Tablet', '1mg', 13, 7),
                                                                           ('Spironolactone', 'Tablet', '25mg', 14, 8),
                                                                           ('Trazodone', 'Tablet', '50mg', 15, 9),
                                                                           ('Ursodiol', 'Capsule', '250mg', 16, 10),
                                                                           ('Vardenafil', 'Tablet', '10mg', 17, 11),
                                                                           ('Wellbutrin', 'Tablet', '150mg', 18, 1),
                                                                           ('Xanax', 'Tablet', '0.5mg', 19, 2),
                                                                           ('Yohimbine', 'Tablet', '5mg', 20, 3),
                                                                           ('Zithromax', 'Tablet', '500mg', 1, 4);

INSERT INTO divisions (name, lat, lng) VALUES
                                           ('DHAKA', 23.8103, 90.4125),
                                           ('CHITTAGONG', 22.3569, 91.7832),
                                           ('KHULNA', 22.8456, 89.5403),
                                           ('BARISHAL', 22.7136, 90.3535),
                                           ('RAJSHAHI', 24.3636, 88.6241),
                                           ('RANGPUR', 25.7439, 89.2752),
                                           ('MYMENSINGH', 24.7471, 90.4203),
                                           ('SYLHET', 24.8949, 91.8687);

INSERT INTO districts (name, lat, lng, division_id) VALUES
                                                        ('Dhaka', 23.7115253, 90.4111451, 1),
                                                        ('Faridpur', 23.6070822, 89.8429406, 1),
                                                        ('Gazipur', 24.0022858, 90.4264283, 1),
                                                        ('Gopalganj', 23.0050857, 89.8266059, 1),
                                                        ('Jamalpur', 24.937533, 89.937775, 7),
                                                        ('Kishoreganj', 24.444937, 90.776575, 1),
                                                        ('Madaripur', 23.164102, 90.1896805, 1),
                                                        ('Manikganj', 23.8644, 90.0047, 1),
                                                        ('Munshiganj', 23.5422, 90.5305, 1),
                                                        ('Mymensingh', 24.7471, 90.4203, 7),
                                                        ('Narayanganj', 23.63366, 90.496482, 1),
                                                        ('Narsingdi', 23.932233, 90.71541, 1),
                                                        ('Netrokona', 24.870955, 90.727887, 7),
                                                        ('Rajbari', 23.7574305, 89.6444665, 1),
                                                        ('Shariatpur', 23.2423, 90.4348, 1),
                                                        ('Sherpur', 25.0204933, 90.0152966, 7),
                                                        ('Tangail', 24.2513, 89.9167, 1),
                                                        ('Bogura', 24.8465228, 89.377755, 5),
                                                        ('Joypurhat', 25.0968, 89.0227, 5),
                                                        ('Naogaon', 24.7936, 88.9318, 5),
                                                        ('Natore', 24.420556, 89.000282, 5),
                                                        ('Nawabganj', 24.5965034, 88.2775122, 1),
                                                        ('Pabna', 23.998524, 89.233645, 5),
                                                        ('Rajshahi', 24.3745, 88.6042, 5),
                                                        ('Sirajgonj', 24.4533978, 89.7006815, 5),
                                                        ('Dinajpur', 25.6217061, 88.6354504, 6),
                                                        ('Gaibandha', 25.328751, 89.528088, 6),
                                                        ('Kurigram', 25.805445, 89.636174, 6),
                                                        ('Lalmonirhat', 25.9923, 89.2847, 6),
                                                        ('Nilphamari', 25.931794, 88.856006, 6),
                                                        ('Panchagarh', 26.3411, 88.5541606, 6),
                                                        ('Rangpur', 25.7558096, 89.244462, 6),
                                                        ('Thakurgaon', 26.0336945, 88.4616834, 6),
                                                        ('Barguna', 22.0953, 90.1121, 4),
                                                        ('Barishal', 22.7010, 90.3535, 4),
                                                        ('Bhola', 22.685923, 90.648179, 4),
                                                        ('Jhalokati', 22.6406, 90.1987, 4),
                                                        ('Patuakhali', 22.3596316, 90.3298712, 4),
                                                        ('Pirojpur', 22.5841, 89.9720, 4),
                                                        ('Bandarban', 22.1953275, 92.2183773, 2),
                                                        ('Brahmanbaria', 23.9570904, 91.1119286, 2),
                                                        ('Chandpur', 23.2332585, 90.6712912, 2),
                                                        ('Chattogram', 22.335109, 91.834073, 2),
                                                        ('Cumilla', 23.4682747, 91.1788135, 2),
                                                        ('Cox''s Bazar', 21.4272, 92.0058, 2),
                                                        ('Feni', 23.0159, 91.3976, 2),
                                                        ('Khagrachari', 23.119285, 91.984663, 2),
                                                        ('Lakshmipur', 22.942477, 90.841184, 2),
                                                        ('Noakhali', 22.869563, 91.099398, 2),
                                                        ('Rangamati', 22.7324, 92.2985, 2),
                                                        ('Habiganj', 24.374945, 91.41553, 8),
                                                        ('Maulvibazar', 24.482934, 91.777417, 8),
                                                        ('Sunamganj', 25.0658042, 91.3950115, 8),
                                                        ('Sylhet', 24.8897956, 91.8697894, 8),
                                                        ('Bagerhat', 22.651568, 89.785938, 3),
                                                        ('Chuadanga', 23.6401961, 88.841841, 3),
                                                        ('Jashore', 23.16643, 89.2081126, 3),
                                                        ('Jhenaidah', 23.5448176, 89.1539213, 3),
                                                        ('Khulna', 22.815774, 89.568679, 3),
                                                        ('Kushtia', 23.901258, 89.120482,3 ),
                                                        ('Magura', 23.487337, 89.419956, 3),
                                                        ('Meherpur', 23.762213, 88.631821, 3),
                                                        ('Narail', 23.172534, 89.512672, 3),
                                                        ('Satkhira', 22.7185, 89.0705, 3);

INSERT INTO areas (name, lat, lng, district_id) VALUES
                                                    ('Gulshan-1', 23.7806615, 90.4112899, 1),
                                                    ('Banani', 23.7947552, 90.3954059, 1),
                                                    ('Dhanmondi', 23.7470303, 90.3655623, 1),
                                                    ('Mirpur-1', 23.7945624, 90.3435587, 1),
                                                    ('Uttara', 23.8766322, 90.3576884, 1),
                                                    ('Shahbag', 23.7348, 90.3929, 1),
                                                    ('Mirpur', 23.8223, 90.3654, 1),
                                                    ('Mohammadpur', 23.7639, 90.3610, 1),
                                                    ('Farmgate', 23.7537, 90.3844, 1),
                                                    ('Motijheel', 23.7345, 90.4146, 1),
                                                    ('Karwan Bazar', 23.7503, 90.4005, 1),
                                                    ('New Market', 23.7303, 90.4081, 1),
                                                    ('Science Laboratory', 23.7368, 90.3779, 1),
                                                    ('Lalbagh', 23.7115, 90.4088, 1),
                                                    ('Badda', 23.7876, 90.4236, 1),
                                                    ('Rampura', 23.7622, 90.4173, 1),
                                                    ('Mohakhali', 23.7799, 90.4066, 1),
                                                    ('Khilgaon', 23.7384, 90.4334, 1),
                                                    ('Pallabi', 23.8313, 90.3632, 1),
                                                    ('Banasree', 23.7740, 90.4335, 1),
                                                    ('Baridhara', 23.8037, 90.4231, 1),
                                                    ('Niketon', 23.7974, 90.4043, 1),
                                                    ('Wari', 23.7154, 90.4035, 1),
                                                    ('Jatrabari', 23.7191, 90.4557, 1),
                                                    ('Mirpur DOHS', 23.8213, 90.3683, 1),
                                                    ('Baily Road', 23.7294, 90.4023, 1),
                                                    ('Mohakhali DOHS', 23.7993, 90.4082, 1),
                                                    ('Shyamoli', 23.7607, 90.3714, 1 ),
                                                    ('Banglamotor', 23.7486, 90.3852, 1),
                                                    ('Malibagh', 23.7484, 90.4290, 1),
                                                    ('Rampura Bridge', 23.7593, 90.4272, 1),
                                                    ('Hazaribagh', 23.7247, 90.4167, 1),
                                                    ('Azimpur', 23.7211, 90.3880, 1),
                                                    ('Tejgaon', 23.7617, 90.4064, 1),
                                                    ('Kamalapur', 23.7313, 90.4164, 1),
                                                    ('Agargaon', 23.7753, 90.3715, 1),
                                                    ('Mirpur-10', 23.8129, 90.3630, 1),
                                                    ('Mirpur-2', 23.8052, 90.3656, 1),
                                                    ('Mohammadpur Town Hall', 23.7678, 90.3606, 1),
                                                    ('Mohammadpur Bus Stand', 23.7651, 90.3624, 1),
                                                    ('Kalabagan', 23.7494, 90.3748, 1),
                                                    ('Shantinagar', 23.7311, 90.4178, 1),
                                                    ('Hatirpool', 23.7443, 90.3926, 1),
                                                    ('Mohakhali Bus Stand', 23.7889, 90.4080, 1),
                                                    ('Bongshal', 23.7151, 90.4093, 1),
                                                    ('Gulistan', 23.7226, 90.4165, 1),
                                                    ('Malibagh Railgate', 23.7523, 90.4292, 1),
                                                    ('Malibagh Mor', 23.7546, 90.4228, 1),
                                                    ('Kuril Biswa Road', 23.8056, 90.4254, 1);

INSERT INTO prescriptions (doctor_id, patient_id, area_id) VALUES
                                                               (1, 1, 1),
                                                               (1, 2, 1),
                                                               (1, 3, 2),
                                                               (1, 4, 2),
                                                               (1, 5, 3),
                                                               (2, 6, 1),
                                                               (2, 7, 2),
                                                               (2, 8, 2),
                                                               (2, 9, 3),
                                                               (2, 10, 3),
                                                               (3, 11, 1),
                                                               (3, 12, 1),
                                                               (3, 13, 2),
                                                               (3, 14, 2),
                                                               (3, 15, 3),
                                                               (4, 16, 1),
                                                               (4, 17, 1),
                                                               (4, 18, 2),
                                                               (4, 19, 2),
                                                               (4, 20, 3),
                                                               (1, 21, 1),
                                                               (1, 22, 2),
                                                               (1, 23, 3),
                                                               (1, 24, 1),
                                                               (1, 25, 2),
                                                               (2, 26, 3),
                                                               (2, 27, 1),
                                                               (2, 28, 2),
                                                               (2, 29, 3),
                                                               (2, 30, 1),
                                                               (3, 31, 2),
                                                               (3, 32, 3),
                                                               (3, 33, 1),
                                                               (3, 34, 2),
                                                               (3, 35, 3),
                                                               (4, 36, 1),
                                                               (4, 37, 2),
                                                               (4, 38, 3),
                                                               (4, 39, 1),
                                                               (4, 40, 2),
                                                               (1, 41, 3),
                                                               (1, 42, 1),
                                                               (1, 43, 2),
                                                               (1, 44, 3),
                                                               (1, 45, 1),
                                                               (2, 46, 2),
                                                               (2, 47, 3),
                                                               (2, 48, 1),
                                                               (2, 49, 2),
                                                               (2, 50, 3),
                                                               (3, 51, 1),
                                                               (3, 52, 2),
                                                               (3, 53, 3),
                                                               (3, 54, 1),
                                                               (3, 55, 2),
                                                               (4, 56, 3),
                                                               (4, 57, 1),
                                                               (4, 58, 2),
                                                               (4, 59, 3),
                                                               (4, 60, 1),
                                                               (1, 61, 2),
                                                               (1, 62, 3),
                                                               (1, 63, 1),
                                                               (1, 64, 2),
                                                               (1, 65, 3),
                                                               (2, 66, 1),
                                                               (2, 67, 2),
                                                               (2, 68, 3),
                                                               (2, 69, 1),
                                                               (2, 70, 2),
                                                               (3, 71, 3),
                                                               (3, 72, 1),
                                                               (3, 73, 2),
                                                               (3, 74, 3),
                                                               (3, 75, 1),
                                                               (4, 76, 2),
                                                               (4, 77, 3),
                                                               (4, 78, 1),
                                                               (4, 79, 2),
                                                               (4, 80, 3),
                                                               (1, 81, 1),
                                                               (1, 82, 2),
                                                               (1, 83, 3),
                                                               (1, 84, 1),
                                                               (1, 85, 2),
                                                               (2, 86, 3),
                                                               (2, 87, 1),
                                                               (2, 88, 2),
                                                               (2, 89, 3),
                                                               (2, 90, 1),
                                                               (3, 91, 2),
                                                               (3, 92, 3),
                                                               (3, 93, 1),
                                                               (3, 94, 2),
                                                               (3, 95, 3),
                                                               (4, 96, 1),
                                                               (4, 97, 2),
                                                               (4, 98, 3),
                                                               (4, 99, 1),
                                                               (4, 100, 2);


INSERT INTO prescription_drugs (prescription_id, drug_id) VALUES
                                                              (1, 1),
                                                              (1, 2),
                                                              (1, 3),
                                                              (2, 4),
                                                              (2, 5),
                                                              (2, 6),
                                                              (3, 7),
                                                              (3, 8),
                                                              (3, 9),
                                                              (4, 10),
                                                              (4, 11),
                                                              (4, 12),
                                                              (5, 13),
                                                              (5, 14),
                                                              (5, 15),
                                                              (6, 16),
                                                              (6, 17),
                                                              (6, 18),
                                                              (7, 19),
                                                              (7, 20),
                                                              (7, 21),
                                                              (8, 22),
                                                              (8, 23),
                                                              (8, 24),
                                                              (9, 25),
                                                              (9, 26),
                                                              (9, 27),
                                                              (10, 28),
                                                              (10, 29),
                                                              (10, 30),
                                                              (11, 31),
                                                              (11, 32),
                                                              (11, 33),
                                                              (12, 34),
                                                              (12, 35),
                                                              (12, 36),
                                                              (13, 37),
                                                              (13, 38),
                                                              (13, 39),
                                                              (14, 40),
                                                              (14, 41),
                                                              (14, 42),
                                                              (15, 43),
                                                              (15, 44),
                                                              (15, 45),
                                                              (16, 46),
                                                              (16, 47),
                                                              (16, 48),
                                                              (17, 49),
                                                              (17, 50),
                                                              (17, 51),
                                                              (18, 52),
                                                              (18, 53),
                                                              (18, 54),
                                                              (19, 55),
                                                              (19, 56),
                                                              (19, 57),
                                                              (20, 58),
                                                              (20, 59),
                                                              (20, 60),
                                                              (21, 61),
                                                              (21, 62),
                                                              (21, 63),
                                                              (22, 64),
                                                              (22, 65),
                                                              (22, 66),
                                                              (23, 67),
                                                              (23, 68),
                                                              (23, 69),
                                                              (24, 70),
                                                              (24, 71),
                                                              (24, 72),
                                                              (25, 73),
                                                              (25, 74),
                                                              (25, 75),
                                                              (26, 76),
                                                              (26, 77),
                                                              (26, 78),
                                                              (27, 79),
                                                              (27, 80),
                                                              (27, 81),
                                                              (28, 2),
                                                              (28, 8),
                                                              (28, 4),
                                                              (29, 5),
                                                              (29, 6),
                                                              (30, 1),
                                                              (30, 4),
                                                              (30, 7),
                                                              (31, 10),
                                                              (31, 13),
                                                              (31, 16),
                                                              (32, 19),
                                                              (32, 22),
                                                              (32, 25),
                                                              (33, 28),
                                                              (33, 31),
                                                              (33, 34),
                                                              (34, 37),
                                                              (34, 40),
                                                              (34, 43),
                                                              (35, 46),
                                                              (35, 49),
                                                              (35, 52),
                                                              (36, 55),
                                                              (36, 58),
                                                              (36, 61),
                                                              (37, 64),
                                                              (37, 67),
                                                              (37, 70),
                                                              (38, 73),
                                                              (38, 76),
                                                              (38, 79),
                                                              (39, 2),
                                                              (39, 5),
                                                              (2, 2),
                                                              (2, 5),
                                                              (2, 8),
                                                              (3, 11),
                                                              (3, 14),
                                                              (3, 17),
                                                              (4, 20),
                                                              (4, 23),
                                                              (4, 26),
                                                              (5, 29),
                                                              (5, 32),
                                                              (5, 35),
                                                              (6, 38),
                                                              (6, 41),
                                                              (6, 44),
                                                              (7, 47),
                                                              (7, 50),
                                                              (7, 53),
                                                              (8, 56),
                                                              (8, 59),
                                                              (8, 62),
                                                              (9, 65),
                                                              (9, 68),
                                                              (9, 71),
                                                              (10, 74),
                                                              (10, 77),
                                                              (10, 80),
                                                              (11, 3),
                                                              (11, 6),
                                                              (12, 1),
                                                              (12, 4),
                                                              (12, 7),
                                                              (13, 10),
                                                              (13, 13),
                                                              (13, 16),
                                                              (14, 19),
                                                              (14, 22),
                                                              (14, 25),
                                                              (15, 28),
                                                              (15, 31),
                                                              (15, 34),
                                                              (16, 37),
                                                              (16, 40),
                                                              (16, 43),
                                                              (17, 46),
                                                              (17, 49),
                                                              (17, 52),
                                                              (18, 55),
                                                              (18, 58),
                                                              (18, 61),
                                                              (19, 64),
                                                              (19, 67),
                                                              (19, 70),
                                                              (20, 73),
                                                              (20, 76),
                                                              (20, 79),
                                                              (21, 2),
                                                              (21, 5),
                                                              (22, 2),
                                                              (22, 5),
                                                              (22, 8),
                                                              (23, 11),
                                                              (23, 14),
                                                              (23, 17),
                                                              (24, 20),
                                                              (24, 23),
                                                              (24, 26),
                                                              (25, 29),
                                                              (25, 32),
                                                              (25, 35),
                                                              (26, 38),
                                                              (26, 41),
                                                              (26, 44),
                                                              (27, 47),
                                                              (27, 50),
                                                              (27, 53),
                                                              (28, 56),
                                                              (28, 59),
                                                              (28, 62),
                                                              (29, 65),
                                                              (29, 68),
                                                              (29, 71),
                                                              (30, 74),
                                                              (30, 77),
                                                              (30, 80),
                                                              (31, 3),
                                                              (31, 6),
                                                              (40, 1),
                                                              (41, 2),
                                                              (42, 3),
                                                              (43, 4),
                                                              (44, 5),
                                                              (45, 6),
                                                              (46, 7),
                                                              (47, 8),
                                                              (48, 9),
                                                              (49, 10),
                                                              (50, 11),
                                                              (51, 12),
                                                              (52, 13),
                                                              (53, 14),
                                                              (54, 15),
                                                              (55, 16),
                                                              (56, 17),
                                                              (57, 18),
                                                              (58, 19),
                                                              (59, 20),
                                                              (60, 21),
                                                              (61, 22),
                                                              (62, 23),
                                                              (63, 24),
                                                              (64, 25),
                                                              (65, 26),
                                                              (66, 27),
                                                              (67, 28),
                                                              (68, 29),
                                                              (69, 30),
                                                              (70, 31),
                                                              (71, 32),
                                                              (72, 33),
                                                              (73, 34),
                                                              (74, 35),
                                                              (75, 36),
                                                              (76, 37),
                                                              (77, 38),
                                                              (78, 39),
                                                              (79, 40),
                                                              (80, 41),
                                                              (81, 42),
                                                              (82, 43),
                                                              (83, 44),
                                                              (84, 45),
                                                              (85, 46),
                                                              (86, 47),
                                                              (87, 48),
                                                              (88, 49),
                                                              (89, 50),
                                                              (90, 51),
                                                              (91, 52),
                                                              (92, 53),
                                                              (93, 54),
                                                              (94, 55),
                                                              (95, 56),
                                                              (96, 57),
                                                              (97, 58),
                                                              (98, 59),
                                                              (99, 60),
                                                              (100, 1),
                                                              (100, 2),
                                                              (100, 3),
                                                              (100, 4);